# Generated by Django 3.1.2 on 2020-10-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
